### ISSUE TITLE
tiktok-live fail with "TypeError: Cannot read property 'Status' of undefined"

### ISSUE THREAD

**Issue by zylaxabi** [UnCrevard/tiktok-live#3]
the site also can't find the live, so they probably changed something on their end. Is there a workaround?

**Comment by UnCrevard** [comment]
new update test it out !

maybe it's an offline live or another tiktok mystery 😅

**Comment by zylaxabi** [comment]
It happens on live streams. But when you go to the link on their website it responds with a "Cannot find this live".  So no workaround?
